#!/bin/zsh

HOME=~
ROOT=$HOME/code/dotfiles
CONFIG=$HOME/.config

# cleanup
unlink $HOME/.zshrc
unlink $HOME/.gitconfig

unlink $CONFIG/tmux
unlink $CONFIG/alacritty
unlink $CONFIG/starship.toml

# setup
ln -s $ROOT/zsh/zshrc $HOME/.zshrc
ln -s $ROOT/git/config $HOME/.gitconfig

ln -s $ROOT/tmux $CONFIG/tmux
ln -s $ROOT/alacritty $CONFIG/alacritty
ln -s $ROOT/starship/starship.toml $CONFIG/starship.toml
