#!/bin/zsh

ROOT=~/code/dotfiles

HOME=~
ln -sf $ROOT/zsh/zshrc $HOME/.zshrc
ln -sf $ROOT/git/config $HOME/.gitconfig

CONFIG=~/.config
ln -sf $ROOT/tmux $CONFIG/tmux
ln -sf $ROOT/alacritty $CONFIG/alacritty
ln -sf $ROOT/starship/starship.toml $CONFIG/starship.toml
