#!/bin/zsh

HOME=~
ROOT=$HOME/code/dotfiles
CONFIG=$HOME/.config

# cleanup
unlink $HOME/.zshrc
unlink $HOME/.zprofile
unlink $HOME/.gitconfig
unlink $HOME/.rgignore

unlink $CONFIG/nvim
unlink $CONFIG/tmux
unlink $CONFIG/alacritty
unlink $CONFIG/starship.toml
unlink $CONFIG/youtube-dl

# setup
ln -s $ROOT/zsh/zshenv $HOME/.zshenv
ln -s $ROOT/zsh/zshrc $HOME/.zshrc
ln -s $ROOT/zsh/zprofile $HOME/.zprofile
ln -s $ROOT/git/gitconfig $HOME/.gitconfig
ln -s $ROOT/rg/rgignore $HOME/.rgignore

ln -s $ROOT/nvim $CONFIG/nvim
ln -s $ROOT/tmux $CONFIG/tmux
ln -s $ROOT/alacritty $CONFIG/alacritty
ln -s $ROOT/starship/starship.toml $CONFIG/starship.toml
ln -s $ROOT/youtube-dl $CONFIG/youtube-dl
